AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Jersey API - learning.aws::aws-lambda-jersey
Resources:
  AwsLambdaJerseyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: learning.aws.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/aws-lambda-jersey-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Environment:
        Variables:
          TABLE_NAME: !Ref orders
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt orders.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON
  orders:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
#        - AttributeName: user
#          AttributeType: S
#        - AttributeName: amount
#          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TableName: orders


Outputs:
  AwsLambdaJerseyApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: AwsLambdaJerseyApi
